
name: UEDownload

inputs:
  UnrealEnginePAT:
    required: true
    type: string
  UnrealStorageRoot:
    required: false
    type: string
    default: "."
    
runs:
  using: "composite"
  steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
    
    - name: Disk info
      shell: pwsh
      run: Get-PSDrive

    - name: Clone Unreal Engine
      shell: pwsh
      run: |
        cd ${{ inputs.UnrealStorageRoot }}/
        git clone https://${{ inputs.UnrealEnginePAT }}@github.com/EpicGames/UnrealEngine.git --depth 1 --branch 5.0.3-release

    - name: Disk info after clone
      shell: pwsh
      run: Get-PSDrive
      
    #- name: Get cached engine
     # id: cached-engine
     # uses: actions/cache@v3
     # with:
     #   path: "${{ inputs.UnrealStorageRoot }}/UnrealEngine"
     #   key: "CachedEngine"

    #- name: SymLink Unreal Engine clone directory
     # shell: pwsh
      #run: New-Item -Path ./UnrealEngine -ItemType SymbolicLink -Value C:/UnrealEngine

    #- name: Checkout Unreal
     # uses: actions/checkout@v3
      #if: ${{ !steps.cached-engine.outputs.cache-hit }}
     # with:
      #  repository: EpicGames/UnrealEngine
       # token: 
        #path: ${{ inputs.UnrealStorageRoot }}/UnrealEngine
        #fetch-depth: 1
        #ref: "5.0.3-release"

    - name: copy gitdepsignore file
      shell: pwsh
      run:  Copy-Item -Path "./.gitdepsignore" -Destination ${{ inputs.UnrealStorageRoot }}/UnrealEngine -Force          

    - name: Download Unreal Engine dependencies
      shell: pwsh
      run: |
        cd ${{ inputs.UnrealStorageRoot }}/UnrealEngine
        dir
        #UE5.1 .\Engine\Binaries\DotNET\GitDependencies\win-x64\GitDependencies.exe 
        .\Engine\Binaries\DotNET\GitDependencies.exe
        ./GenerateProjectFiles.bat

     - name: Disk info after dependencies
      shell: pwsh
      run: Get-PSDrive
      
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'          

    - name: Install ue4cli
      shell: pwsh
      run: pip install ue4cli

    - name: Set root ue4cli
      shell: pwsh
      run: ue4 setroot "${{ inputs.UnrealStorageRoot }}/UnrealEngine"

    - name: Build Engine
      shell: pwsh
      run: ue4 build-target UnrealEditor Development #needs to be UE4Editor on ue4
