name: UnrealCodeBuild

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      enginePath:
        required: true
        type: string
      pluginPath:
        required: true
        type: string
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      - uses: actions/checkout@v3
      
      - name: debug
        run: |
          echo ${{ github.event.inputs.enginePath }}
          echo ${{ github.event.inputs.pluginPath }}
          dir
          
              
      - name: download and extract-7z-action
        run: |
          $TargetEnginePath = "${{ github.event.inputs.enginePath }}";
          if( TargetEnginePath.StartsWith("http") )
          {
             Invoke-Webrequest -URI $TargetEnginePath -OutFile "./DownloadedEngine.7z"
             $TargetEnginePath = "./DownloadedEngine.7z"
          }
          ./7za.exe x $TargetEnginePath -oEngine
        
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: install ue4cli
        run: pip install ue4cli
        
      - name: Set root ue4cli
        run: ue4 setroot "./Engine"
        
      - name: Create Plugins folder and move plugins
        run: |
          New-Item "./Plugins" -itemType Directory
          Copy-Item -Path "{{ github.event.inputs.pluginPath }}/*" -Destination "./Plugins/Plugin" -Recurse -Force
          cd Plugins/Plugin
          dir
      - name: Run ue4cli
        run: ue4 build # -NoPCH -NoSharedPCH -DisableUnity
