name: UnrealCodeBuild

# Controls when the workflow will run
inputs:
  enginePath:
    required: true
    type: string
  pluginPath:
    required: true
    type: string
    
# Steps represent a sequence of tasks that will be executed as part of the job

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - name: debug
      shell: pwsh
      run: |
        echo ${{ inputs.enginePath }}
        echo ${{ inputs.pluginPath }}
        echo ${{ github.action_path }}
        dir

    - name: download and extract-7z-action
      shell: pwsh
      run: |
        $TargetEnginePath = "${{ inputs.enginePath }}";
        if( $TargetEnginePath -like 'http*' )
        {
           Invoke-Webrequest -URI $TargetEnginePath -OutFile "./DownloadedEngine.7z"
           $TargetEnginePath = "./DownloadedEngine.7z"
        }
        ${{ github.action_path }}/7za.exe x $TargetEnginePath -oEngine

    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: install ue4cli
      shell: pwsh
      run: pip install ue4cli

    - name: Set root ue4cli
      shell: pwsh
      run: ue4 setroot "./Engine"

    - name: Create Plugins folder and move plugins
      shell: pwsh
      run: |
        New-Item "./Plugins" -itemType Directory
        Copy-Item -Path "${{ inputs.pluginPath }}/*" -Destination "./Plugins/Plugin" -Recurse -Force
        cd Plugins/Plugin
        dir

    - name: Run ue4cli
      shell: pwsh
      run: ue4 build # -NoPCH -NoSharedPCH -DisableUnity
