name: UnrealCodeBuild

# Controls when the workflow will run
inputs:
  enginePath:
    required: true
    type: string
  enginePathIsDownload:
    type: boolean
    required: true
  pluginPath:
    required: true
    type: string
  engineCacheId:
    required: false
    type: string
  outputFolderName:
    required: false
    type: string
    default: "Plugin"
    
# Steps represent a sequence of tasks that will be executed as part of the job

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
        
    - name: Telemetry
      shell: pwsh
      continue-on-error: true
      run: |
        $Agent = "${{ github.repository }}";
        $BuilderVersion = "1.0";
        $body = "{\""pluginName\"": \""CodeBuilder\"", \""appId\"":\""$Agent\"", \""versionFriendly\"":\""$BuilderVersion\"" }";
        curl.exe -H "Content-Type: application/json" -H "User-Agent: $Agent"--request POST -d $body https://api.codebuilder.guganana.com/api/usage;
        
    - name: Get cached engine
      id: cached-engine
      uses: actions/cache@v3
      if: ${{ inputs.enginePathIsDownload }}
      with:
        path: ${{ github.action_path }}/Engine.7z
        key: "${{ inputs.enginePath }}+${{ inputs.engineCacheId }}"

    - name: download and extract-7z-action
      if: ${{ inputs.enginePathIsDownload && !steps.cached-engine.outputs.cache-hit }}
      shell: pwsh
      run: Invoke-Webrequest -URI ${{ inputs.enginePath }} -OutFile ${{ github.action_path }}/Engine.7z
        
    - name: Copy compressed engine to working dir
      shell: pwsh
      if: ${{ !inputs.enginePathIsDownload }}
      run:  Copy-Item -Path "${{ inputs.enginePath }}" -Destination "${{ github.action_path }}/Engine.7z" -Force
      
    - name: extract-7z-action
      shell: pwsh
      run: ${{ github.action_path }}/7za.exe x "${{ github.action_path }}/Engine.7z" -o${{ github.action_path }}/Engine

    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: install ue4cli
      shell: pwsh
      run: pip install ue4cli

    - name: Set root ue4cli
      shell: pwsh
      run: ue4 setroot "${{ github.action_path }}/Engine"

    - name: Create Plugins folder and move plugins
      shell: pwsh
      run: |
        $PluginFolderPath = "UnrealCodeBuilder/${{ inputs.outputFolderName }}"
        New-Item "UnrealCodeBuilder/" -itemType Directory
        New-Item $PluginFolderPath -itemType Directory
        Copy-Item -Path "${{ inputs.pluginPath }}/*" -Destination $PluginFolderPath -Recurse -Force
        dir

    - name: Run ue4cli
      shell: pwsh
      run: cd UnrealCodeBuilder/${{ inputs.outputFolderName }}; ue4 build # -NoPCH -NoSharedPCH -DisableUnity
