name: UnrealCodeBuild

# Controls when the workflow will run
inputs:
  enginePath:
    required: true
    type: string
  pluginPath:
    required: true
    type: string
  pluginPathIsDownload:
    type: boolean
    
# Steps represent a sequence of tasks that will be executed as part of the job

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - name: debug
      shell: pwsh
      run: |
        echo ${{ inputs.enginePath }}
        echo ${{ inputs.pluginPath }}
        echo ${{ github.action_path }}
        dir

    - name: download and extract-7z-action
      shell: pwsh
      if: ${{ inputs.pluginPathIsDownload  == 'true' }}
      run: |
        $TargetEnginePath = "${{ github.action_path }}/DownloadedEngine.7z"
        Invoke-Webrequest -URI ${{ inputs.pluginPath }} -OutFile $TargetEnginePath
        ${{ github.action_path }}/7za.exe x $TargetEnginePath -o${{ github.action_path }}/Engine
        dir ${{ github.action_path }}/Engine
        
    - name: extract-7z-action
      shell: pwsh
      if: ${{ inputs.pluginPathIsDownload  == 'false' }}
      run: ${{ github.action_path }}/7za.exe x "${{ inputs.pluginPath }}" -o${{ github.action_path }}/Engine

    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: install ue4cli
      shell: pwsh
      run: pip install ue4cli

    - name: Set root ue4cli
      shell: pwsh
      run: ue4 setroot "${{ github.action_path }}/Engine"

    - name: Create Plugins folder and move plugins
      shell: pwsh
      run: |
        New-Item "${{ github.action_path }}/Plugins" -itemType Directory
        New-Item "${{ github.action_path }}/Plugins/Plugin" -itemType Directory
        Copy-Item -Path "${{ inputs.pluginPath }}/*" -Destination "${{ github.action_path }}/Plugins/Plugin" -Recurse -Force
        cd ${{ github.action_path }}/Plugins/Plugin
        dir

    - name: Run ue4cli
      shell: pwsh
      run: ue4 build # -NoPCH -NoSharedPCH -DisableUnity
