name: UnrealCodeBuild

inputs:
  projectPath:
    required: true
    type: string
  command:
    required: true
    type: string
  args:
    required: false
    type: string
    default: ""
    
runs:
  using: "composite"
  steps:
    - name: Running command '${{ inputs.command }}'
      shell: pwsh
      run: |
        cd ${{ inputs.projectPath }}
        ${{ github.action_path }}/${{ inputs.command }}.ps1 ${{ inputs.args }}
      
