name: UnrealCodeBuild

inputs:
  projectPath:
    required: false
    type: string
    default: "./"
    
runs:
  using: "composite"
  steps:
    - name: Parsing metadata into environment
      shell: pwsh
      run: |
        cd ${{ inputs.projectPath }}
        ${{ github.action_path }}/parse-metadata.ps1
      
      
