
name: PrepareEngineFromPackage

inputs:
  outputDir:
    required: true
    type: string
  githubToken:
    required: true
    type: string
    
runs:
  using: "composite"
  steps:

    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '3.1.x'
      
    - name: Install Engine nuget package
      shell: pwsh
      run: |
        echo "a${{ inputs.githubToken }}"
        dotnet nuget add source --username ${{ github.actor }} --password "${{ inputs.githubToken }}" --store-password-in-clear-text --name github "https://nuget.pkg.github.com/guganana/index.json"
        nuget install MinimalUEBuilds -OutputDirectory "${{ inputs.outputDir }}"
        dir "${{ inputs.outputDir }}"
        
