# This is a basic workflow to help you get started with Actions

name: UEGet

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Clone Unreal Engine
        shell: pwsh
        env: 
          TOKEN: ${{ secrets.UNREAL_TOKEN }}
        run: |
          New-Item C:\UnrealEngine -itemType Directory
          cd C:\UnrealEngine
          git clone https://$TOKEN@github.com/EpicGames/UnrealEngine.git --depth 1 --branch 5.0.3-release
          
      #- name: Get cached engine
       # id: cached-engine
       # uses: actions/cache@v3
       # with:
       #   path: "C:/UnrealEngine"
       #   key: "CachedEngine"

      #- name: Checkout Unreal
       # uses: actions/checkout@v3
        #if: ${{ !steps.cached-engine.outputs.cache-hit }}
        #with:
        #  repository: EpicGames/UnrealEngine
         # token: ${{ secrets.UNREAL_TOKEN }}
          #path: ./UnrealEngineTemp
          #fetch-depth: 1
         # ref: "5.0.3-release"

      - name: Copy Unreal into largest drive
        shell: pwsh
        run:  Copy-Item -Path "./UnrealEngineTemp" -Destination C:/UnrealEngine -Force -Recurse
        
      - name: copy gitdepsignore file
        shell: pwsh
        run:  Copy-Item -Path "./.gitdepsignore" -Destination C/:UnrealEngine -Force          
          
      - name: Download Unreal Engine dependencies
        shell: pwsh
        run: |
          cd C:/UnrealEngine
          dir
          #UE5.1 .\Engine\Binaries\DotNET\GitDependencies\win-x64\GitDependencies.exe --exclude="Templates" --exclude="Engine/Content" --exclude="Engine/Extras" --exclude="FeaturePacks" --exclude="Samples" --max-retries=30
          .\Engine\Binaries\DotNET\GitDependencies.exe --exclude="Templates" --exclude="Engine/Content" --exclude="Engine/Extras" --exclude="FeaturePacks" --exclude="Samples" --max-retries=30
          Get-Volume
          GenerateProjectFiles.bat

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'          
        
      - name: Install ue4cli
        shell: pwsh
        run: pip install ue4cli

      - name: Set root ue4cli
        shell: pwsh
        run: ue4 setroot "C:/UnrealEngine"

      - name: Build Engine
        shell: pwsh
        run: ue4 build-target UnrealEditor Development #needs to be UE4Editor on ue4
